---
title: Highlight
name: Highlight
collection: atoms
notes: |
  `.vd-highlight`
---
<div class="vd-highlight">
  <div class="container-fluid">
    <h3>Title here</h3>
    <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab illum deleniti soluta itaque, vel impedit, aperiam voluptatibus repudiandae minima nostrum, quaerat quisquam libero sit aspernatur enim quae natus, nam molestias!</p>
  </div>
</div>
