---
title: List Bare
name: list-bare
collection: atoms
notes: |
  `.vd-list-bare` strip list-like appearance from lists by removing their bullets, and any indentation.
---
<ul class="vd-list-bare">
  <li>Lorem ipsum dolor sit amet.</li>
  <li>Tempora consectetur, aliquam nisi iure.</li>
  <li>Explicabo velit, aliquam beatae quam?</li>
  <li>Quam soluta obcaecati nesciunt molestias.</li>
  <li>Dolor eius vel commodi rem!</li>
</ul>
