---
title: Paragraph
name: Paragraph
collection: atoms
notes: |
  Wrap the text in `.vd-content` to set a `max-width` to the paragraphs for readability purposes.
---
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum, obcaecati veritatis ipsam officia necessitatibus fuga, tempora vel unde libero soluta excepturi? Cumque dolorem, atque soluta. Obcaecati vel vero ipsam corporis.</p>
