---
title: Search Form
name: Search-form
collection: atoms
notes: |
  ##### Usage : `search-form`
---

<div class="input-group search-form">
  <label class="sr-only" for="search-form">Champ de rechercher</label>
  <input id="search-form" type="text" class="form-control" placeholder="Rechercher">
  <span class="input-group-btn">
    <button class="btn" type="button"><i class="fa fa-search" aria-hidden="true"></i></button>
  </span>
</div>
