env:
  browser: true
  es6: true
extends: airbnb
ecmaFeatures:
  blockBindings: true
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
    - VariableDeclarator: {"var": 2, "let": 2, "const": 3}
  linebreak-style:
    - error
    - unix
  no-var: 2
  quotes:
    - error
    - single
  semi:
    - error
    - always
