---
title: access-nav
name: access-nav
collection: molecules
notes: |
  Add an accessible nav with link containing accesskey
---
<nav class="vd-access-nav" aria-label="menu accessibilité">
  <ul>
      <li>
        <a class="btn btn-primary" accesskey="0" href="#" title="[Alt+0] Page d'accueil du site">Accueil</a>
      </li>
      <li>
        <a class="btn btn-primary" accesskey="1" href="#nav-primary" title="[Alt+1] Menu de navigation de la page">Menu de navigation de la page</a>
      </li>
      <li>
        <a class="btn btn-primary" accesskey="2" href="#main" title="[Alt+2] Debut du contenu de la page">Début du contenu de la page</a>
      </li>
      <li>
        <a class="btn btn-primary" accesskey="3" href="#" title="[Alt+3] Page de contact">Page de contact</a>
      </li>
      <li>
        <a class="btn btn-primary" accesskey="4" href="#" title="[Alt+4] Plan du site du Canton de Vaud">Plan du site</a>
      </li>
      <li><a class="btn btn-primary" accesskey="5" href="#search-form" title="[Alt+5] Accès au champ de recherche">Accès au champ de recherche</a></li>
      <li>
        <a class="btn btn-primary" accesskey="6" href="#" title="[Alt+6] Accès à l'index thématique">Thèmes</a>
      </li>
      <li>
        <a class="btn btn-primary" accesskey="7" href="#" title="[Alt+7] Accès à la navigation par autorités">Autorités</a>
      </li>
      <li>
        <a class="btn btn-primary" accesskey="8" href="#" title="[Alt+8] Page d'aide pour les personnes en situation de handicap">Page d'aide pour les personnes en situation de handicap</a>
      </li>
    </ul>
</nav>
