---
title: access-nav
name: Access-nav
collection: molecules
notes: |
  Add an accessible nav with link containing accesskey
---
<nav class="vd-access-nav">
  <ul>
      <li>
        <a class="btn btn-primary" accesskey="0" href="#" title="[Alt+0] Page d'accueil du site">Accueil</a>
      </li>
      <li>
        <a class="btn btn-primary" accesskey="1" href="#2" title="[Alt+1] Menu de navigation de la page">Menu de navigation de la page</a>
      </li>
      <li>
        <a class="btn btn-primary" accesskey="2" href="#" title="[Alt+2] Debut du contenu de la page">D&eacute;but du contenu de la page</a>
      </li>
      <li>
        <a class="btn btn-primary" accesskey="3" href="#" title="[Alt+3] Page de contact">Page de contact</a>
      </li>
      <li>
        <a class="btn btn-primary" accesskey="4" href="#" title="[Alt+4] Plan du site du Canton de Vaud">Plan du site</a>
      </li>
      <li>Acc&egrave;s au champ recherche</li>
      <li>
        <a class="btn btn-primary" accesskey="6" href="#" title="[Alt+6] Acc&amp;egrave;s à l'index th&amp;eacute;matique">Thèmes</a>
      </li>
      <li>
        <a class="btn btn-primary" accesskey="7" href="#" title="[Alt+7] Acc&amp;egrave;s &amp;agrave; la navigation par autorit&amp;eacute;s">Autorités</a>
      </li>
      <li>
        <a class="btn btn-primary" accesskey="8" href="#" title="[Alt+8] Page d'aide pour les personnes en situation de handicap">Page d'aide pour les personnes en situation de handicap</a>
      </li>
    </ul>
</nav>
