---
title: Blockquote
name: Blockquote
collection: molecules
notes: |
  If you want to add a media, add the `.vd-blockquote-media` class to the `blockquote` element.
---
<blockquote class="blockquote vd-blockquote-media">
  <img class="img-fluid img-circle" src="http://placehold.it/120x120" alt="Portr">
  <p>La démocratie ne se découpe pas en morceaux dont on ne choisirait que les meilleurs.</p>
  <footer class="blockquote-footer">Pascal Broulis, Conseil d'État de Vaud</footer>
</blockquote>
