---
title: card
name: Card
collection: molecules
notes: |
---
<div class="vd-card">
  <div class="container">
    <div class="row">
      <div class="col-sm-4">
        <img class="img-fluid rounded-circle" src="https://randomuser.me/api/portraits/women/66.jpg" alt="Card image cap">
      </div>
      <div class="col-sm-8">
        <div class="card-block vd-card-block">
          <h5 class="card-title vd-card-title">Card title</h5>
          <p class="card-text vd-card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <ul class="vd-list-links">
            <li>
              <a href="#">Go somewhere</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
