---
title: FAQ Item
name: faq-item
collection: molecules
notes: |
---
<article id="faq-{% if faq_id %}{{ faq_id }}{% else %}id{% endif %}">
  <h4>Puis-je contester les faits figurant dans le rapport de police ?</h4>
  <p>Si vous contestez tout ou une partie du contenu d’un rapport de police, vous devez le signaler par écrit au SAN dans un délai de 20 jours dès réception de l’avis d’ouverture de procédure. Selon vos arguments, le SAN peut suspendre la procédure
    administrative jusqu’à l’issue de l’action pénale afin de connaître quelle-s infraction-s a-ont été retenue-s par le magistrat. Dès que la sentence pénale est prononcée, le SAN tient pour établis les faits retenus.</p>
  <footer>
    <dl class="row small text-muted">
      <dt class="col-sm-3">Categories</dt>
      <dd class="col-sm-9">
        <a href="#">Lorem ipsum</a>,
        <a href="#">Dolor</a>,
        <a href="#">Sit amet</a>
      </dd>

      <dt class="col-sm-3">Auteur</dt>
      <dd class="col-sm-9">Vestibulum id ligula porta felis euismod semper eget lacinia odio sem nec elit.</dd>
    </dl>
    <p>
      <a href="#" class="btn btn-secondary btn-sm vd-btn-chevron-t">Retour</a>
    </p>
  </footer>
</article>
