---
title: Fixed bottom container
name: fixed-bottom-container
collection: molecules
notes: |
  - Custom class `.vd-fixed-bottom` to stick a container fixed to the bottom of the page.
  - You can also use the class with the default bootstrap breakpoints as suffixes (ie: `.vd-fixed-bottom-sm-down`, `.vd-fixed-bottom-xs-only` or `.vd-fixed-bottom-xl-up`)
---

<div class="vd-fixed-bottom-sm-only vd-fixed-bottom-xs-only">
  <a href="#" class="btn btn-primary btn-block">Commander un extrait en ligne</a>
</div>
