---
title: Form input required
name: form-input-required
collection: molecules
notes: |
---
<p>Les champs obligatoire sont suivis par <strong><abbr title="required">*</abbr></strong>.</p>
<div class="form-group">
  <label for="testInput">Label</label> <strong><abbr title="required">*</abbr></strong>
  <input class="form-control" type="text" id="testInput" name="firstname" value="" required aria-required="true">
</div>
