---
title: List Icons
name: list-icon
collection: molecules
notes: |
  Add the `.vd-list-icons` class to a list to set icons as bullets.

  Add an icon from [FontAwesome](http://fontawesome.io/icons/) before the list-item: `<span class="fa fa-info-circle" aria-hidden="true"></span>`
---
<ul class="vd-list-icons">
  <li>
    <span class="fa fa-info-circle" aria-hidden="true"></span> <a href="mailto:info.spi@vd.ch">info.spi@vd.ch</a>
  </li>
  <li>
    <span class="fa fa-map-marker" aria-hidden="true"></span> <a href="#0">voir sur la carte</a>
  </li>
</ul>
