---
title: Logo Etat Alternate
name: logo-etat-alternate
collection: molecules
notes: |
  This logo is only used on the homepage. Elsewhere, use the default logo.
---
<a href="../accueil" class="vd-logo" aria-labelledby="aria-vd-logo">
  <div class="vd-logo-img">
    <img src="../build/svg/logo/logo.svg" class="img-fluid" alt="Logo du canton de Vaud" />
  </div>
  <div class="vd-logo-title">
    <div id="aria-vd-logo">Site officiel<span class="sr-only"> de l'État de Vaud</span></div>
    <img src="../build/svg/ETATVAUD.svg" alt="État de Vaud" aria-hidden="true" />
  </div>
</a>
