---
title: Logo Etat Alternate
name: logo-etat-alternate
collection: molecules
notes: |
  This is the logo for the État de Vaud without the coat of arms.
---
<a href="../accueil" class="vd-logo" aria-labelledby="aria-vd-logo">
  <div class="vd-logo-title ml-2">
    <div id="aria-vd-logo">Site officiel<span class="sr-only"> de l'État de Vaud</span></div>
    <img src="../build/svg/ETATVAUD.svg" alt="État de Vaud" aria-hidden="true" />
  </div>
</a>
