---
title: Logo Etat
name: logo-etat
collection: molecules
notes: |
  This is the logo for the État de Vaud website.
---
<a href="../accueil" class="vd-logo" aria-labelledby="aria-vd-logo">
  <div class="vd-logo-title">
    <div id="aria-vd-logo">Site officiel<span class="sr-only"> de l'État de Vaud</span></div>
    <img src="../build/svg/ETATVAUD.svg" alt="État de Vaud" aria-hidden="true" />
  </div>
</a>
