---
title: Logo Etat
name: logo-etat
collection: molecules
notes: |
  This is the logo for the État de Vaud
---
<div class="vd-logo">
  <div class="vd-logo__logo mr-2">
    <img src="../build/svg/logo/logo.svg" class="img-fluid" alt="Canton de Vaud" />
  </div>
  <div class="vd-logo__title">
    <span id="aria-vd-logo">Site officiel<span class="sr-only"> de l'État de Vaud</span></span>
    <img src="../build/svg/ETATVAUD.svg" alt="État de Vaud" aria-labelledby="aria-vd-logo" />
  </div>
</div>
