---
title: Nav Pagination
name: nav-pagination
collection: molecules
bootstrap:
notes: |
  Use "next / previous" pagination instead of numbered pages.
---
<nav>
  <h3 class="sr-only">Pagination</h2>
  <ul class="list-inline row text-xxs-center">
    <li class="list-inline-item"><a href="#" class="btn btn-secondary btn-sm vd-btn-chevron-l">Précédent</a></li>
    <li class="list-inline-item"><a href="#" class="btn btn-secondary btn-sm vd-btn-chevron-r">Suivant</a></li>
  </ul>
</nav>
