---
title: Nav Pagination
name: nav-pagination
collection: molecules
bootstrap:
notes: |
  Use "next / previous" pagination instead of numbered pages.
---
<nav>
  <h3 class="sr-only">Pagination</h2>
  <ul class="list-inline row">
    <li class="col-xxs-6 text-xxs-right"><a href="#" class="btn btn-primary">Précédent</a></li>
    <li class="col-xxs-6 text-xxs-left"><a href="#" class="btn btn-primary">Suivant</a></li>
  </ul>
</nav>
