---
title: Nav
name: Nav
collection: molecules
bootstrap: http://v4-alpha.getbootstrap.com/components/navs/#base-nav
notes: |
  Use a `<ul>` list to obtain a bare navigation that is not inline.
---
<nav class="nav nav-inline hidden-sm-down">
  <h2 class="sr-only">Sous-navigation</h2>
  <a class="nav-link active" href="../autorites"><span class="sr-only">page active: </span>Autorités</a>
  <a class="nav-link" href="#">Annuaire</a>
  <a class="nav-link" href="#">Agenda</a>
  <a class="nav-link" href="#">Contact</a>
  <a class="nav-link" href="../connexion">Espace Sécurisé</a>
</nav>
