---
title: Pagination vertical
name: Pagination-vertical
collection: molecules
notes: |
  You can apply the following class to the list element to style it:
  `.success`, `.warning`, `.current`, `.disabled`
---
<nav aria-label="Page navigation">
  <ul class="vd-vertical-pagination">
    <li class="vd-page-item success">
        <span class="vd-page-item-bullet"><i aria-hidden="true" class="fa fa-check"></i></span>
        <a class="vd-page-item-title" href="">Données du demandeur</a>
    </li>
    <li class="vd-page-item warning">
        <span class="vd-page-item-bullet"><i aria-hidden="true" class="fa fa-question"></i></span>
        <a class="vd-page-item-title" href="">Identité de l'enfant</a>
    </li>
    <li class="vd-page-item current">
        <span class="vd-page-item-bullet">3</span>
        <a class="vd-page-item-title" href="">Auteur du signalement</a>
    </li>
    <li class="vd-page-item">
        <span class="vd-page-item-bullet">4</span>
        <a class="vd-page-item-title" href="">Données 4</a>
    </li>
    <li class="vd-page-item disabled">
        <span class="vd-page-item-bullet">5</span>
        <a class="vd-page-item-title" href="">Données 5</a>
    </li>
    <li class="vd-page-item disabled">
      <span class="vd-page-item-bullet">6</span>
      <span class="vd-page-item-title" href="">Données 6</span>
    </li>
    <li class="vd-page-item">
      <span class="vd-page-item-bullet">7</span>
      <a class="vd-page-item-title" href="">Données 7</a>
    </li>
    <li class="vd-page-item">
      <span class="vd-page-item-bullet">12</span>
      <a class="vd-page-item-title" href="">Envoyer le formulaire</a>
    </li>
  </ul></nav>
