---
title: Secure Tabs
name: secure-tabs
collection: molecules
notes: |
  Wrap your nav component in a `.vd-bg-pattern-purple` div and obtain tabs for the secure area of the website.
---
<div class="vd-bg-pattern-purple">
  <div class="container vd-nav-tabs-secure">
    <div class="fa fa-lock fa-lg" aria-hidden="true"></div>
    <ul class="nav">
      <li class="nav-item">
        <a class="nav-link active" href="#">Active</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
  </div>
</div>
