---
title: Social Icons
name: social-icons
collection: molecules
notes: |
  You can use all the [Fontawesome icons](http://fontawesome.io/icons/) in these icons.
---
<ul class="list-inline vd-social-icons">
  <li class="list-inline-item">
    <a class="vd-social-icon" href="#0" title="Facebook" aria-label="Like us on Facebook"><span class="fa fa-facebook" aria-hidden="true"></span></a>
  </li>
  <li class="list-inline-item">
    <a class="vd-social-icon" href="#0" title="Twitter" aria-label="Like us on Twitter"><span class="fa fa-twitter" aria-hidden="true"></span></a>
  </li>
  <li class="list-inline-item">
    <a class="vd-social-icon" href="#0" title="Youtube" aria-label="Like us on Youtube"><span class="fa fa-youtube-play" aria-hidden="true"></span></a>
  </li>
  <li class="list-inline-item">
    <a class="vd-social-icon" href="#0" title="Instagram" aria-label="Like us on Instagram"><span class="fa fa-instagram" aria-hidden="true"></span></a>
  </li>
  <li class="list-inline-item">
    <a class="vd-social-icon" href="#0" title="Mail" aria-label="Send us a Mail"><span class="fa fa-envelope" aria-hidden="true"></span></a>
  </li>
</ul>
