---
title: Social Icons
name: social-icons
collection: molecules
notes: |
  You can use all the [Fontawesome icons](http://fontawesome.io/icons/) in these icons.
---
<h2 class="{% if social_icons_header_hidden %}sr-only{% else %}vd-section-title mb-1{% endif %}">Partager</h2>

<ul class="list-inline vd-social-icons">
  <li class="list-inline-item">
    <a class="vd-social-icon" href="#0" title="Mail" aria-label="Send us a Mail"><span class="fa fa-envelope" aria-hidden="true"></span></a>
  </li>
  <li class="list-inline-item">
    <a class="vd-social-icon" href="#0" title="Twitter" aria-label="Like us on Twitter"><span class="fa fa-twitter" aria-hidden="true"></span></a>
  </li>
  <li class="list-inline-item">
    <a class="vd-social-icon" href="#0" title="Facebook" aria-label="Like us on Facebook"><span class="fa fa-facebook" aria-hidden="true"></span></a>
  </li>
  <li class="list-inline-item">
    <a class="vd-social-icon" href="#0" title="Linkedin" aria-label="Like us on Linkedin"><span class="fa fa-linkedin" aria-hidden="true"></span></a>
  </li>
  <li class="list-inline-item">
    <a class="vd-social-icon" href="#0" title="WhatsApp" aria-label="Like us on WhatsApp"><span class="fa fa-whatsapp" aria-hidden="true"></span></a>
  </li>
</ul>
