---
title: teaser-card
name: Teaser-card
collection: molecules
bootstrap: https://v4-alpha.getbootstrap.com/components/card/#background-variants
notes: |
  Use the classes `.vd-card-lightgray`, `.vd-card-darkgray`, `.vd-card-black` or any bootstrap background variant classes (ie: `.card-primary`, `.card-success`, etc.) to alter the color of the card.
  In case of dark background, use the class `.card-inverse` to display a nice bright  text.
---

<div class="card vd-teaser-card vd-card-lightgray">
  <img class="card-img-top w-100" src="http://placehold.it/700x200" alt="Card image cap">
  <div class="card-block">
    <h4 class="card-title mb-0">Card title</h4>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
  </div>
</div>
