---
title: Vertical pagination
name: Vertical-pagination
collection: molecules
notes: |
  ##### Usage : `vertical-pagination`
  ##### Options :
  - **option** - Type
---
<nav aria-label="Page navigation">
  <ul class="vertical-pagination">
    <li class="success">
      <div>
        <span class="bullet"><i aria-hidden="true" class="fa fa-check"></i></span>
      </div>
      <div>
        <a class="title" href="">Données du demandeur</a>
      </div>
    </li>
    <li class="warning">
      <div>
        <span class="bullet"><i aria-hidden="true" class="fa fa-question"></i></span>
      </div>
      <div>
        <a class="title" href="">Identité de l'enfant</a>
      </div>
    </li>
    <li class="current">
      <div>
        <span class="bullet">3</span>
      </div>
      <div>
        <a class="title" href="">Auteur du signalement</a>
      </div>
    </li>
    <li>
      <div>
        <span class="bullet">4</span>
      </div>
      <div>
        <a class="title" href="">Données 4</a>
      </div>
    </li>
    <li class="disabled">
      <div>
        <span class="bullet">5</span>
      </div>
      <div>
        <a class="title" href="">Données 5</a>
      </div>
    </li>
    <li class="disabled">
      <div>
        <span class="bullet">6</span>
      </div>
      <div>
        <span class="title" href="">Données 6</span>
      </div>
    </li>
    <li>
      <div>
        <span class="bullet">7</span>
      </div>
      <div>
        <a class="title" href="">Données 7</a>
      </div>
    </li>
    <li>
      <div>
        <span class="bullet">12</span>
      </div>
      <div>
        <a class="title" href="">Envoyer le formulaire</a>
      </div>
    </li>
  </ul></nav>
