---
title: Vertical pagination
name: Vertical-pagination
collection: molecules
notes: |
  You can apply the following class to the list element to style it:
  `.success`, `.warning`, `.current`, `.disabled`
---
<nav aria-label="Page navigation">
  <ul class="vertical-pagination">
    <li class="success">
        <span class="bullet"><i aria-hidden="true" class="fa fa-check"></i></span>
        <a class="title" href="">Données du demandeur</a>
    </li>
    <li class="warning">
        <span class="bullet"><i aria-hidden="true" class="fa fa-question"></i></span>
        <a class="title" href="">Identité de l'enfant</a>
    </li>
    <li class="current">
        <span class="bullet">3</span>
        <a class="title" href="">Auteur du signalement</a>
    </li>
    <li>
        <span class="bullet">4</span>
        <a class="title" href="">Données 4</a>
    </li>
    <li class="disabled">
        <span class="bullet">5</span>
        <a class="title" href="">Données 5</a>
    </li>
    <li class="disabled">
      <span class="bullet">6</span>
      <span class="title" href="">Données 6</span>
    </li>
    <li>
      <span class="bullet">7</span>
      <a class="title" href="">Données 7</a>
    </li>
    <li>
      <span class="bullet">12</span>
      <a class="title" href="">Envoyer le formulaire</a>
    </li>
  </ul></nav>
